### PR TITLE
Quality coverage concept

### PR DESCRIPTION
**Pull request by EvanBarbour3**
## Features
- Added `FilterTrait`
- Added `LimitTrait`
- Added `ModelTrait`
- Fixed bugs with updating model active flag
- Minor doc changes to keep **scrutinizer** happy
- Added more testing for `Merchant`, `Locations` and `Ips`

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@wnowicki Here's the changes I managed to get done

**Comment by wnowicki** [comment]
Where are the additional tests?

**Comment by 00eadeyemi** [comment]
@wnowicki ready for review

**Comment by wnowicki** [comment]
Perfect! Well done!

**Pull request merged**
