### PR TITLE
Validation, beautiful validation

### PR DESCRIPTION
**Pull request by EvanBarbour3**
## Features
- Added validation for product limits (127177411)

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@srleach

**Comment by EvanBarbour3** [comment]
@sped2773 Can you review this?

**Comment by sped2773** [comment]
- Don't go to 2dp just whole numbers 
- No max length limit set use max length 2 (once dp removed)

**Comment by EvanBarbour3** [comment]
@sped2773 Ready for review again

**Comment by sped2773** [comment]
- Values not updating

**Comment by EvanBarbour3** [comment]
@sped2773 ready again

**Pull request merged**
