### PR TITLE
Documentator

### PR DESCRIPTION
**Pull request by srleach**
:hand:

### CODE REVIEW

**Comment by srleach** [comment]
@EvanBarbour3 we need to run through this and check all works as planned, if so we can merge away :)

**Comment by srleach** [comment]
@EvanBarbour3 how did running this go?

**Comment by srleach** [comment]
@EvanBarbour3 ?

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3 Can you please look at this now?

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3 Please could you run and review? This has been pending for nearly 3 months 👎

**Comment by EvanBarbour3** [comment]
@srleach Can't even merge in develop. gonna revert commit and then start it again, see whats happening

**Comment by srleach** [comment]
What's the state of this now @EvanBarbour3 ?

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by srleach** [comment]
@EvanBarbour3

**Comment by wnowicki** [comment]
@EvanBarbour3 and @srleach can we just agree what's the state of it and who should be taking actions?

**Comment by srleach** [comment]
I'm awaiting @EvanBarbour3 review, I think he had some trouble running it because of the age of the PR. 

Next steps needed:

- Need to revert composer lock and json
- Need to update from develop
- Need to `composer require` the phpdoc library as in the composer.json above
- Need to recommit changes

@EvanBarbour3 are you happy doing the above, or would you like me to do this?

**Comment by srleach** [comment]
@EvanBarbour3 see above comment please

**Comment by EvanBarbour3** [comment]
@srleach I did some stuff 23 days ago, which were the things above? I got stuck at the .phar file which was required, I think maybe just putting this in will solve some stuff and we won't have much left to do?

**Comment by srleach** [comment]
@EvanBarbour3 Ok, I'll double check the phar file, though it shouldn't be required as phpdoc is required as a dependency rather than a phar.

**Comment by srleach** [comment]
@EvanBarbour3 When reverting a commit you did not reapply all changes, so `composer docs` was not defined.

**Comment by srleach** [comment]
@EvanBarbour3 missed reapplying the phpdoc.xml config file too

**Comment by srleach** [comment]
@EvanBarbour3 Please test this now, it should work for you 

## Usage:

`sudo composer docs`

From within the box. Also try outside of the box, you should be told off...

**Comment by wnowicki** [comment]
- conflict easy to resolve, just remove `composer.lock` and then freshly require
- @EvanBarbour3 and @srleach as I can see you both commits there please agree between both of you if it's ready or not yet

**Comment by wnowicki** [comment]
I don't see any issues why it can't be merged. But let's have 3 minutes chat tomorrow.

**Comment by wnowicki** [comment]
I have some issues with creating box

**Comment by wnowicki** [comment]
@srleach should I expect this?

```
This project needs the graphviz package installed.
Attempting to install package. This may require you to enter a password...
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

**Comment by wnowicki** [comment]
```
Problem 1
    - Installation request for zendframework/zend-serializer 2.8.0 -> satisfiable by zendframework/zend-serializer[2.8.0].
    - zendframework/zend-serializer 2.8.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.21) does not satisfy that requirement.
  Problem 2
    - zendframework/zend-serializer 2.8.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.21) does not satisfy that requirement.
    - phpdocumentor/phpdocumentor v2.9.0 requires zendframework/zend-serializer ~2.1 -> satisfiable by zendframework/zend-serializer[2.8.0].
    - Installation request for phpdocumentor/phpdocumentor v2.9.0 -> satisfiable by phpdocumentor/phpdocumentor[v2.9.0].
```

**Comment by EvanBarbour3** [comment]
@srleach Tested this. Got a few errors such as `This project needs the graphviz package installed.
`. 

Massive output in the terminal such as:
```
No summary was found for this file
No summary for method
No summary for property
```

**Comment by srleach** [comment]
@EvanBarbour3 That's fine. That's expected output when people don't put docblocks ;)

I'll spend 20m on this tonight, see if we can get a less verbose output on the build, and also ensure that we can create the docs on php <5.6

**Comment by srleach** [comment]
Closing pending compatibility solution with earlier PHP versions

**Pull request closed without merging**
