### PR TITLE
Hover help changes

### PR DESCRIPTION
**Pull request by EvanBarbour3**
## Features
- Added help information to various inputs
- Added Colours to application statuses

[Delivers [#128407127](https://www.pivotaltracker.com/story/show/128407127)]

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@sped2773 Can you review this please?

**Comment by EvanBarbour3** [comment]
@sped2773 Changes made

**Comment by sped2773** [comment]
Happy to merge @wnowicki as we are releasing I'll leave merge to you :-)

**Comment by sped2773** [comment]
Happy to merge, this should be in release how do you want to handle @wnowicki?

**Pull request merged**
