### PR TITLE
Beta feature

### PR DESCRIPTION
**Pull request by KrekoG**
### Added
- Beta feature flag (#157690873)

[Delivers [#157690873](https://www.pivotaltracker.com/story/show/157690873)]

### CODE REVIEW

**Comment by KrekoG** [comment]
✋ make sure [base PR](https://github.com/PayBreak/basket/pull/269) is already accepted before merging

**Comment by KrekoG** [comment]
@00eadeyemi Ready for your review

**Comment by 00eadeyemi** [comment]
@EvanBarbour3 @KrekoG the beta flag works fine, however, we are now unable to add users.

**Comment by KrekoG** [comment]
@00eadeyemi I checked this and the issue is also present on dev, so my suggestion would be that it originates from another PR, or that there is a missing setting/configuration somewhere. Investigating further

**Pull request merged**
