### PR TITLE
Hotfix routes

### PR DESCRIPTION
**Pull request by EvanBarbour3**
## Bug Fixes
- Removed validation for at least one application route

[Delivers [#128648421](https://www.pivotaltracker.com/story/show/128648421)]

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@wnowicki Please can you review?

**Comment by wnowicki** [comment]
@EvanBarbour3 please do UAT with @sped2773 first (we can put it TEST if you want)

**Comment by EvanBarbour3** [comment]
@wnowicki If we could put this on test that would be good

**Comment by EvanBarbour3** [comment]
@wnowicki UAT'd by @sped2773 and Gary. can be merged

**Pull request merged**
