### PR TITLE
Super Fix

### PR DESCRIPTION
**Pull request by wnowicki**
## Bug Fixes
- Fixed *Application Link* copy issue 

[126790701](https://www.pivotaltracker.com/story/show/126790701)

### CODE REVIEW

**Comment by wnowicki** [comment]
> **IMPORTANT**
> This time as an exception, please don't delete branch after merge!

**Comment by sped2773** [comment]
Breaking process under duress :rocket:

**Comment by wnowicki** [comment]
yes please

**Comment by sped2773** [comment]
As this is superfix will let you update change log and create release

**Pull request merged**
